name: golang-pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: go Build
        run: |
          go mod tidy
          go build -o jwt .
        env:
          EXTRA_FILES: "LICENSE"

      - name: Create Release
        id: create_release
        uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          force-bump-patch-version: "true"
          changelog-generator-opt: "emojis=true"


      - name: Gets latest created release info
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          # This pulls from the CREATE RELEASE step above,
          # referencing it's ID to get its outputs object,
          # which include a `upload_url`.
          # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: jwt.
          asset_name: jwt
          asset_content_type: application/octet-stream