name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    # defaults:
    #   run:
    #     working-directory: src/
    steps:
      - uses: actions/checkout@v2
      - name: Run go Build
        run: go mod download ; go build .
        env:
          GOARCH: amd64
          GOOS: linux
          EXTRA_FILES: "LICENSE"
      - uses: actions/upload-artifact@v3
        with:
          name: main
          path: main