name: golang-pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: go Build
        run: go mod download ; go build .
        env:
          GOARCH: amd64
          GOOS: linux
          EXTRA_FILES: "LICENSE"

      - name: zip artifact
        run: tar -cvzf jwt.tar.gz jwt


      - name: zip artifact
        run: ls -l

      - name: Create Release
        id: create_release
        uses: go-semantic-release/action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          force-bump-patch-version: "true"
          changelog-generator-opt: "emojis=true"

      # - uses: go-semantic-release/action@v1
      #   id: semrel
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     update-file: package.json
      #     changelog-generator-opt: "emojis=true"

