name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    defaults:
      run:
        working-directory: src/
    steps:
      - uses: actions/checkout@v2
      - name: Run go Build
        run: env ; go mod download ; go build .
